# Generated by Django 3.2.5 on 2022-01-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_item_pomodoro_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='dateStatusCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(verbose_name='Today Date')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='autoCompletePomodoro',
            field=models.BooleanField(default=0, verbose_name='Pomodoro Complete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='itemPriority',
            field=models.IntegerField(default=0, verbose_name='priority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='recurring_task',
            field=models.BooleanField(default=0, verbose_name='Recurring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Date started'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='telegrambotUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telebotId', models.TextField(verbose_name='telegramId')),
                ('event_time', models.DateTimeField(verbose_name='Event Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='Item')),
                ('pomodoro_completed', models.IntegerField(verbose_name='Pomodoro Completed')),
                ('pomodoro_estimated', models.IntegerField(verbose_name='Pomodoro Estimate')),
                ('event_time', models.DateTimeField(verbose_name='Event Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item', models.CharField(max_length=700)),
                ('create_date', models.DateTimeField(verbose_name='Date created')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Date started')),
                ('due_date', models.DateTimeField(verbose_name='Due date')),
                ('status', models.BooleanField(verbose_name='Completed')),
                ('pomodoro_estimate', models.IntegerField(verbose_name='Pomodoro Estimate')),
                ('pomodoro_completed', models.IntegerField(verbose_name='Pomodoro Completed')),
                ('recurring_task', models.BooleanField(verbose_name='Recurring')),
                ('autoCompletePomodoro', models.BooleanField(verbose_name='Pomodoro Complete')),
                ('itemPriority', models.IntegerField(verbose_name='priority')),
                ('tags', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
